# -*- coding: utf-8 -*-
"""10_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtrtqOdl-ys9FOaIavnXp6_5NjPjvXrp

Create a simple self-checkout system.

Prompt for the prices and quantities of three items.

Calculate the subtotal of the items.

Then calculate the tax using a tax rate of 5.5%.

Print out the line items with the quantity and total, and
then print out the subtotal, tax amount, and total.
"""

# Receber dados do usuário
preco1 = input("Digite o preço do item: ")
quant1 = input("Digite a quantidade do item: ")

preco2 = input("Digite o preco do item: ")
quant2 = input("Digite a quantidade do item: ")

preco3 = input("Digite o preco do item: ")
quant3 = input("Digite a quantidade do item: ")

# Converter dados para valores númericos
preco1 = float(preco1)
preco2 = float(preco2)
preco3 = float(preco3)

quant1 = int(quant1)
quant2 = int(quant2)
quant3 = int(quant3)

# Calcular valores de saída
valor1 = quant1 * preco1
valor2 = quant2 * preco2
valor3 = quant3 * preco3

subtotal = valor1 + valor2 + valor3
imposto = subtotal * 5.5
imposto = imposto / 100
total = subtotal + imposto

# Formatar valores de saída
valor1 = round(valor1, 2)
valor2 = round(valor2, 2)
valor3 = round(valor3, 2)

subtotal = round(subtotal, 2)
imposto = round(imposto, 2)
total = round(total, 2)

# Mostrar valores de saída
print(f'Valor item 1: R${valor1}')
print(f'Valor item 2: R${valor2}')
print(f'Valor item 3: R${valor3}')

print(f'Subtotal: R${subtotal}')
print(f'Impostos: R${imposto}')

print(f'total: R${total}')