# -*- coding: utf-8 -*-
"""11_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9rZ3Yd17Q2cmfMYTvhs0jw6_rc8VzCD

Write a program that converts currency.

Specifically, convert euros to U.S. dollars.

Prompt for the amount of money in euros you have, and prompt for the current exchange rate of the euro.

Print out the new amount in U.S. dollars.

The formula for currency conversion is
"""

# amountTo = (amountFrom * rateFrom) / rateTo

# Receber dados do usuário
euros = input("Digite a quantidade de euros: ")
cambio = input("Digite a taxa de cambio atual: ")

# Converter dados para númerico
euros = float(euros)
cambio = float(cambio)

# Calcular os dados de saída
cambio = cambio / 100
dolares = euros * cambio

# Formatar os dados de saída
euros = round(euros, 2)
cambio = round(cambio, 2)
dolares = round(dolares, 2)

# Mostrar os dados de saída
print(f'{euros} euros a uma taxa de cambio de {cambio} equivalem a ${dolares}')