# -*- coding: utf-8 -*-
"""12_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KneFXx4OASXHt4FCfqDhitu0tQljKNx

Create a program that computes simple interest.

Prompt for the principal amount, the rate as a percentage, and the time, and display the amount accrued (principal +
interest).

The formula for simple interest is A = P(1 + rt), where P is the principal amount, r is the annual rate of interest, t is the number of years the amount is invested, and A is the amount at the end of the investment.
"""

# Receber dados do usuário
capital = input("Digite o valor investido: ")
taxa_juros = input("Digite a taxa de juros anual: ")
tempo = input("Digite o tempo de investimento em anos: ")

# Converter dados para númerico
capital = int(capital)
taxa_juros = float(taxa_juros)
tempo = int(tempo)

# Calcular os dados de saída
taxa_juros = taxa_juros / 100
juros = capital * (1 + (taxa_juros * tempo))

# Formatar os dados de saída
round(juros, 2)

# Mostrar os dados de saída
print(f'R${capital} investidos a uma taxa de {taxa_juros}% durante {tempo} anos, equivalem a R${juros}')