# -*- coding: utf-8 -*-
"""13_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-knSmIMlZjQrjCQ9tHIrHXdp084eUk1

Write a program to compute the value of an investment
compounded over time.

The program should ask for the starting amount, the number of years to invest, the interest rate, and the number of periods per year to compound.

The formula you’ll use for this is
A = P(1 + r / n)**nt

where:

• P is the principal amount.

• r is the annual rate of interest.

• t is the number of years the amount is invested.

• n is the number of times the interest is compounded per
year.

• A is the amount at the end of the investment.
"""

# Receber dados do usuário
capital = input("Digite o valor investido: ")
juros = input("Digite a taxa de juros: ")
tempo = input("Digite a duração do investimento: ")
composicao = input("Digite a taxa de composição de juros: ")

# Converter dados para númerico
capital = int(capital)
tempo = int(tempo)
juros = float(juros)
composicao = int(composicao)

# Calcular os dados de saída
juros = juros / 100
montante = capital * ((1 + (juros / composicao)) ** (composicao * tempo))

# Formatar os dados de saída
montante = round(montante, 2)

# Mostrar os dados de saída
print(f'Valor investido: R${capital}')
print(f'Taxa de juros: {juros}%')
print(f'Taxa de composição: {composicao}')
print(f'Tempo de investimento: {tempo}')
print(f'Valor Final: R${montante}')