# -*- coding: utf-8 -*-
"""1_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAnHw-LXGEtLKke6OIwT_OveEfQaaERK

So create a program that prompts for your name and prints
a greeting using your name.
"""

nome = input("Digite o seu nome: ")

print(f'Olá {nome}, prazer em te conhecer!')