# -*- coding: utf-8 -*-
"""3_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UO06i94GgKTvfRoyZFJly02Ss0fjbPcp

Create a program that prompts for a quote and an author.
Display the quotation and author as shown in the example
output.

Example output:

Obi-Wan Kenobi says, "These aren't the droids
you're looking for."
"""

fala = input("Digite uma fala: ")

autor = input("Digite um autor: ")

print(f'{autor} disse: "{fala}"')