# -*- coding: utf-8 -*-
"""4_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rr4SknOYSToQnqYt-h0mq-_9_MJNxdr

Create a simple mad-lib program that prompts for a noun,
a verb, an adverb, and an adjective and injects those into a story that you create.
"""

nome = input("Digite um nome: ")
verbo = input("Digite um verbo: ")
adverbio = input("Digite um advérbio: ")
adjetivo = input("Digite um adjetivo: ")

print(f'O {nome} {verbo} {adverbio}, pois é {adjetivo}')