# -*- coding: utf-8 -*-
"""5_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfv9VROL3iQD6vzkwTEoCLf3XqS62Y7j

Write a program that prompts for two numbers. Print the
sum, difference, product, and quotient of those numbers as
shown in the example output:

10 + 5 = 15

10 - 5 = 5

10 * 5 = 50

10 / 5 = 2
"""

num1 = int(input("Digite um número: "))
num2 = int(input("Digite outro número: "))

soma = num1 + num2
subtr = num1 - num2
multp = num1 * num2
divis = num1 / num2

print(soma)
print(subtr)
print(multp)
print(divis)