# -*- coding: utf-8 -*-
"""6_Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCER8DFWcF9bcl6GfCu6uwyLBzKYUNlX

Create a program that determines how many years you have
left until retirement and the year you can retire.

It should prompt for your current age and the age you want to retire and display the output as shown in the example that follows.

What is your current age? 25

At what age would you like to retire? 65

You have 40 years left until you can retire.

It's 2015, so you can retire in 2055.
"""

import datetime

data_atual = datetime.date.today()

ano_atual = data_atual.year

idade = int(input("Digite a sua idade: "))

idade_aposentado = int(input("Com quantos anos você vai se aposentar? "))

tempo_aposentadoria = idade_aposentado - idade

ano_aposentadoria = ano_atual + tempo_aposentadoria

print(f'Você vai se aposentar em {tempo_aposentadoria} anos')
print(f'Estamos em {ano_atual} e você estará aposentado em {ano_aposentadoria}')